### ISSUE TITLE
Round 2: Initial EDA

### ISSUE THREAD

**Issue by Da-MaRo** [StefanK2ff/capstone-healthy-skin#38]

**Comment by bjzim** [comment]
**EDA - HAM10000 - Metadata (new structure)**

1 + 2 Importing and loading data

3. Data Exploration

3.1 Descriptive Statistics (lesion_id, image_id, dx, dx_type, age, sex, localization, dataset)

3.2 Confronting Emerging Issues (Missing Values in age)

3.3 Relational Statistics (Contingency Analysis on dx: dx_type, sex, localization, dataset; Chi2-Test; Age per Diagnosis)

3.4 Risk Ratio (Localizazion and Melanoma, Localization and basal cell carcinoma, Localization and keratoses)

4 Confronting Emeging Issues (Imbalanced diagnoses; localization; Age and Sex,...) --> _still legacy from earlier version_
